services:
  - type: web
    name: fischer-fintech
    env: static
    buildCommand: yarn install && yarn build
    staticPublishPath: ./out
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate 